#!/usr/bin/env python3

from ev3dev2.motor import MediumMotor, OUTPUT_A, OUTPUT_B
from ev3dev2.sensor.lego import UltrasonicSensor
from ev3dev2.sensor import INPUT_2, INPUT_3
import time

# ==========================
# HARDWARE
# ==========================

direccion = MediumMotor(OUTPUT_A)
traccion = MediumMotor(OUTPUT_B)

us_izq = UltrasonicSensor(INPUT_2)
us_der = UltrasonicSensor(INPUT_3)

# ==========================
# PD SIMPLE
# ==========================

DT = 0.05

KP = 0.35
KD = 0.30

error_anterior = 0

# ==========================
# LOOP
# ==========================
try:
    while True:

        izq = us_izq.distance_centimeters
        der = us_der.distance_centimeters

        error = der - izq

        derivada = (error - error_anterior) / DT

        output = KP * error + KD * derivada

        # Limitamos la velocidad de giro del motor de dirección
        if output > 55:
            output = 55
        if output < -55:
            output = -55

        # Dirección por velocidad continua (sin encoder/calibración)
        direccion.on(speed=output)

        traccion.run_forever(speed_sp=450)

        error_anterior = error

        time.sleep(DT)

except KeyboardInterrupt:
    pass

finally:
    direccion.stop()
    traccion.stop()
